//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Assets.Scripts
{
    public class AgentEventArgs<T> : EventArgs  
    {
        private T _agent;
        public T Agent { get { return _agent; } }

        public AgentEventArgs(T agent)
        {
            _agent = agent;
        }
    }
}

